# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.IntegerField(db_column=b'idClient', primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column=b'Fname', max_length=45)),
                ('surname', models.CharField(db_column=b'Surname', max_length=45)),
                ('phonenumber', models.CharField(db_column=b'PhoneNumber', max_length=45)),
                ('adress', models.CharField(db_column=b'Adress', max_length=45)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idproduct', models.IntegerField(db_column=b'idProduct', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column=b'Name', max_length=45)),
                ('manufacturer', models.CharField(db_column=b'Manufacturer', max_length=45)),
                ('manufacturercountry', models.CharField(db_column=b'ManufacturerCountry', max_length=45)),
                ('category', models.CharField(db_column=b'Category', max_length=45)),
                ('type', models.CharField(db_column=b'Type', max_length=45)),
                ('capacity', models.CharField(db_column=b'Capacity', max_length=45)),
                ('price', models.CharField(db_column=b'Price', max_length=45)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('idstore', models.IntegerField(db_column=b'idStore', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column=b'Name', max_length=45)),
                ('adress', models.CharField(db_column=b'Adress', max_length=45)),
                ('email', models.CharField(db_column=b'Email', max_length=45)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('idorder', models.IntegerField(db_column=b'idOrder')),
                ('date', models.DateField(db_column=b'Date')),
                ('amount', models.CharField(db_column=b'Amount', max_length=45)),
                ('cost', models.CharField(db_column=b'Cost', max_length=45)),
                ('product_idproduct', models.ForeignKey(db_column=b'Product_idProduct', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Polls.Product')),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
